export const TC_APP_INITIALIZE = 'TC_APP_INITIALIZE';

export const TC_SET_VIEW = 'TC_SET_VIEW';
export const TC_ADD_PROGRAM = 'TC_ADD_PROGRAM';
export const TC_REMOVE_PROGRAM = 'TC_REMOVE_PROGRAM';
export const TC_SET_ACTIVE_PROGRAM = 'TC_SET_ACTIVE_PROGRAM';

export const TC_SHOW_DELETE_MODAL = 'TC_SHOW_DELETE_MODAL';
export const TC_HIDE_DELETE_MODAL = 'TC_HIDE_DELETE_MODAL';
