/**
 * Created by Jaison.Jacob on 7/11/2018.
 */
export const SET_USER = 'SET_USER';

export const TOGGLE_HEADER_NAVBAR = 'TOGGLE_HEADER_NAVBAR';
export const SET_BROWSER_SIZE = 'SET_BROWSER_SIZE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_OPT_ICONS = 'TOGGLE_OPT_ICONS';
export const SET_LANDING_MENU = 'SET_LANDING_MENU';
export const SET_SELECTED_LANDING_MENU = 'SET_SELECTED_LANDING_MENU';
export const SET_OPT_BTN_LAYOUT = 'SET_OPT_BTN_LAYOUT';

export const SET_SELECTED_MENU = 'SET_SELECTED_MENU';

export const HOME_OPT_BTN_LAYOUT = 'HOME_OPT_BTN_LAYOUT';
export const TC_OPT_BTN_LAYOUT = 'TC_OPT_BTN_LAYOUT';

export const SET_APPLY_APP = 'SET_APPLY_APP';
